---
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.11
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key

## This would be nice but would make it much more difficult to adopt
## patches from other picocom forks.
#  - repo: https://github.com/pre-commit/mirrors-clang-format
#    rev: v16.0.6
#    hooks:
#      - id: clang-format
